#!/bin/bash

help() {
  echo "Usage:"
  echo "  zsshc authorize list"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  sshc::list_auth
}

run() {
  core $@
}

run $@
